apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: oc-with-results
spec:
  description: >-
    This task runs commands against the cluster provided by user and if not
    provided then where the Task is being executed.

    OpenShift is a Kubernetes distribution from Red Hat which provides oc, the
    OpenShift CLI that complements kubectl for simplifying deployment and
    configuration applications on OpenShift.
  results:
    - name: oc-output
      description: The output from the oc command
  params:
    - default: oc help
      description: The OpenShift CLI arguments to run
      name: SCRIPT
      type: string
    - default: latest
      description: The OpenShift Version to use
      name: VERSION
      type: string
  steps:
    - image: >-
        image-registry.openshift-image-registry.svc:5000/openshift/cli:$(params.VERSION)
      name: oc
      resources: {}
      script: |
        #!/usr/bin/env bash

        [[ "$(workspaces.manifest-dir.bound)" == "true" ]] && \
        cd $(workspaces.manifest-dir.path)

        [[ "$(workspaces.kubeconfig-dir.bound)" == "true" ]] && \
        [[ -f $(workspaces.kubeconfig-dir.path)/kubeconfig ]] && \
        export KUBECONFIG=$(workspaces.kubeconfig-dir.path)/kubeconfig

        $(params.SCRIPT) | tee $(results.oc-output.path)
  workspaces:
    - description: >-
        The workspace which contains kubernetes manifests which we want to apply
        on the cluster.
      name: manifest-dir
      optional: true
    - description: >-
        The workspace which contains the the kubeconfig file if in case we want
        to run the oc command on another cluster.
      name: kubeconfig-dir
      optional: true